version: 1.0.{build}
image: Visual Studio 2017
build:
  verbosity: minimal

configuration:
  - Debug
platform:
  - Any CPU
branches:
  only:
  - master

init:
  - cmd: git config --global core.autocrlf true

before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore Assertions\Assertions.sln --verbosity m
build_script:
  - cmd: dotnet publish Assertions --output %appveyor_build_folder%\dist

clone_depth: 1

test_script:
  - cmd: dotnet test Assertions/Assertions.UnitTests --logger Appveyor

artifacts:
- path: dist
deploy: off
